pyproject.toml

- requests-toolbeltをdependencyから削除
- pyrebase4が依存しているパッケージ
- pyrebase4 4.6.0でパッケージ側でdependencyの登録が漏れていたため暫定で手動で追加していたもの
- pyrebase4 4.7.1のアップデートで解消されたため、こちらからは削除
- package探索時にローカルの`conda/env`にconda環境を構築している場合にそれらも含まれてしまう問題を解消

pyprojectの更新

---

frontend/src/components/Workspace/Visualize/Editor/TimeSeriesItemEditor.tsx
studio/app/common/core/experiment/experiment_writer.py

- https://github.com/oist/optinist/issues/506
- TimeSeriesのVisualize Editor間の選択を切り替えた際に、テキストフィールドの値が更新されない問題を解消
- 併せて別PRで残ってしまっていた不要なprintを削除

Visualizeのサイドバーコンテンツが追従しない問題の修正

---

studio/app/optinist/core/edit_ROI/edit_ROI.py

- #40 の対応の際に、editROI系の処理の対応が漏れていたため修正
- editROIはOUTPUT_DIRへのconfig.yamlの生成・参照がないため、直接configを引数に指定する実装に修正

fix edit roi config

---

frontend/src/store/slice/DisplayData/DisplayDataSlice.ts
studio/app/common/core/workflow/workflow_writer.py

パラメータ変更時のRUNのbug fix
- workflow画面のoutputが更新されない問題
- workflow.yamlのパラメータが更新されていない問題
- mouse2p.tif -> caiman_mc -> caiman_cnmf
1. caiman_cnmfのKを4でRUN_ALL
2. WORKFLOW画面でOUTPUT（cell_roiなど）を確認
3. RECORDSからworkflowファイルをダウンロード
4. caiman_cnmfのKを8に変更してRUN
5. WORKFLOW画面でOUTPUT（cell_roiなど）を確認
- 最新の出力が表示される
6. RECORDSからworkflowファイルをダウンロード
- Kパラメータが4のファイルと変わっている

fix bugs in run

---

frontend/src/api/outputs/Outputs.ts
frontend/src/components/Workspace/Visualize/Plot/BarPlot.tsx
frontend/src/components/Workspace/Visualize/Plot/HeatMapPlot.tsx
frontend/src/components/Workspace/Visualize/Plot/ImagePlot.tsx
frontend/src/components/Workspace/Visualize/Plot/RoiPlot.tsx
frontend/src/components/Workspace/Visualize/Plot/ScatterPlot.tsx
frontend/src/components/Workspace/Visualize/Plot/TimeSeriesPlot.tsx
frontend/src/store/slice/DisplayData/DisplayDataActions.ts
frontend/src/store/slice/DisplayData/DisplayDataSelectors.ts
frontend/src/store/slice/DisplayData/DisplayDataSlice.ts
frontend/src/store/slice/DisplayData/DisplayDataType.ts
studio/app/common/core/utils/file_reader.py
studio/app/common/core/utils/json_writer.py
studio/app/common/dataclass/bar.py
studio/app/common/dataclass/csv.py
studio/app/common/dataclass/heatmap.py
studio/app/common/dataclass/html.py
studio/app/common/dataclass/image.py
studio/app/common/dataclass/scatter.py
studio/app/common/dataclass/timeseries.py
studio/app/common/routers/outputs.py
studio/app/common/schemas/outputs.py
studio/app/optinist/dataclass/caiman.py
studio/app/optinist/dataclass/fluo.py
studio/app/optinist/dataclass/lccd.py
studio/app/optinist/dataclass/roi.py
studio/app/optinist/dataclass/suite2p.py

- Scatter, Bar, HeatMapのプロットにx軸、y軸、プロットタイトルの表示機能を追加
- wrapper関数で対象のdataclassオブジェクトに対して、PlotMetaDataクラスを渡すことでこれらの情報を付加できる
- 各生成グラフの命名等が決まっていないため、現時点ではwrapper関数側への割り当てはなし
- workflow実行後に生成されるjsonファイル(etaのmean_heatmap.jsonなど)に以下のように"meta"フィールドを追記することで動作確認可能
```json
{
"meta": {
"xlabel": "foo",
"ylabel": "bar",
"title": "foo vs bar"
},
"columns": [],
"index": [],
"data": [],
}
```

plotのタイトル表示

---

frontend/src/components/Workspace/Experiment/CollapsibleTable.tsx
frontend/src/components/Workspace/Experiment/ExperimentStatusIcon.tsx
frontend/src/components/Workspace/Experiment/ExperimentTable.tsx
frontend/src/store/slice/Experiments/Experiments.test.ts
frontend/src/store/slice/Experiments/ExperimentsSelectors.ts
frontend/src/store/slice/Experiments/ExperimentsType.ts
frontend/src/store/slice/Experiments/ExperimentsUtils.ts

- RECORDS画面のデフォルトソートをTimestamp(started_at)降順に変更
- Timestampの表記を、finished_atがあるものは`{started_at} - {finished_at} (elapsed {elapsed time} sec)`のフォーマットに変更
- レイアウトについては、3行の表示かつ列の幅を固定している
- Function別のエラーについて、アイコンクリックでエラーメッセージを表示

improve records view

---

frontend/src/api/experiments/Experiments.ts
frontend/src/api/workflow/Workflow.ts
frontend/src/store/slice/AlgorithmNode/AlgorithmNodeSlice.ts
frontend/src/store/slice/Experiments/ExperimentsActions.ts
frontend/src/store/slice/Experiments/ExperimentsSlice.ts
frontend/src/store/slice/FlowElement/FlowElementSlice.ts
frontend/src/store/slice/InputNode/InputNodeSlice.ts
frontend/src/store/slice/Pipeline/PipelineHook.ts
frontend/src/store/slice/Pipeline/PipelineSlice.ts
frontend/src/store/slice/RightDrawer/RightDrawerSlice.ts
frontend/src/store/slice/Workflow/WorkflowActions.ts
frontend/src/store/test/record/RecordReproduce.test.ts
studio/app/common/core/workflow/workflow.py
studio/app/common/core/workflow/workflow_builder.py
studio/app/common/core/workflow/workflow_reader.py
studio/app/common/core/workflow/workflow_writer.py
studio/app/common/routers/experiment.py
studio/app/common/routers/workflow.py
studio/app/common/schemas/experiment.py
studio/app/common/schemas/workflow.py
studio/tests/app/common/core/workflow/test_workflow_reader.py
studio/tests/app/common/core/workflow/test_workflow_writer.py

- reproduceの際にRUNを実行せずとも結果のVisualizeが可能なように修正
- fetchとresponse内容が重複することや、実行内容からexperiments/fetch -> workflow/fetchにAPIエンドポイントやスキーマのリファクタを実施
- before
- experiments/fetch
- workflow/reproduce
- after
- workflow/fetch
- workflow/reproduce

reproduce outputs

---

frontend/src/components/Workspace/Experiment/ExperimentTable.tsx

Records画面のsortアイコン(矢印)をアクティブなカラムのみ表示
- 非表示のカラムはホバー時に表示される

only active sort icon to be visible

---

frontend/src/components/Workspace/Experiment/Button/ReproduceButton.tsx
frontend/src/store/slice/Workspace/WorkspaceSlice.ts

reproduceボタンクリック時に確認のダイアログを追加
reproduce実行後、workflow画面に自動的に遷移するよう調整

improve reproduce

---

frontend/src/components/Workspace/FlowChart/FlowChart.tsx
frontend/src/components/common/CurrentPipelineInfo.tsx
frontend/src/store/slice/Pipeline/PipelineSelectors.ts
frontend/src/store/slice/Workspace/WorkspaceSelector.ts
frontend/src/store/slice/Workspace/WorkspaceSlice.ts
frontend/src/store/slice/Workspace/WorkspaceType.ts

workflow画面およびvisualize画面の実行中workflow情報欄にworkspaceの情報を追加
表示はマルチユーザーモードの場合のみ
その他UIの修正として、workflow名・workspace名が長い場合は...での省略表示およびホバーでのPopover表示を追加

add workspace info to left menu

---

docker-compose.dev.yml
docker-compose.yml
frontend/.env.example
frontend/src/const/API.ts

- FE dotenv の整理
- アプリケーションのportに関連する設定を .env へ集約
@ReiHashimoto 
少し別件となりますが、このPRに合わせて、以下の修正を取り込んでおいていただければと思います。
- https://github.com/arayabrain/optinist-for-server/pull/218

update .env template

---

frontend/src/components/Workspace/FlowChart/Buttons/RunButtons.tsx
studio/app/optinist/wrappers/caiman/motion_correction.py

複数Workflow同時実行時のエラー解消の一環として、以下の対応を実施
- caiman_mcのmemmapファイルのprefixにfunction_idを使用してユニーク化
- https://github.com/arayabrain/optinist-for-server/pull/191 と同等の対応ですが、uuidではなくfunction_idを使用しています
- RUN ALL, RUNボタンの連打防止
- useRefでのフラグ管理とフラグ更新に3秒のwaitで対応（時間等は根拠が明確ではないので調整の余地あり）
- 連打によって`The name all is already used by another rule`の`CreateRuleException`が発生するため
- 複数画面で検証している中で、ボタンクリックの際に画面へのフォーカスとボタンクリックで2回クリックが必要で、その過程で必要以上に連打してしまった際に気付きました

fix multiple run

---

studio/app/optinist/wrappers/caiman/cnmf.py

caiman_cnmfのNWBファイル保存に関して、以下の問題を解消
- コンソール上で以下のwarning
```
UserWarning: RoiResponseSeries 'Fluorescence': The second dimension of data does not match the length of rois, but instead the first does. Data is oriented incorrectly and should be transposed.
```
- NWBファイルをnwbinspectorでチェックした際に以下のCRITICALエラー
```
0  CRITICAL
===========
0.0  caiman_cnmf.nwb: check_roi_response_series_dims - 'RoiResponseSeries' object at location '/processing/ophys/caiman_cnmf_5ptm4hgue5/Fluorescence'
Message: The second dimension of data does not match the length of rois, but instead the first does. Data is oriented incorrectly and should be transposed.
0.1  caiman_cnmf.nwb: check_data_orientation - 'RoiResponseSeries' object at location '/processing/ophys/caiman_cnmf_5ptm4hgue5/Fluorescence'
Message: Data may be …
```

fix RoiResponseSeries data's shape

---

.pre-commit-config.yaml

sample-dataなど大きいファイルをリポジトリで管理するケースが多いため、当面はpre-commitから除外

remove large file check on pre-commit

---

frontend/src/components/Workspace/Experiment/Button/DeleteButton.tsx
frontend/src/components/Workspace/Experiment/Button/ReproduceButton.tsx
frontend/src/components/Workspace/Experiment/ExperimentTable.tsx
frontend/src/components/Workspace/FlowChart/Buttons/ClearWorkflow.tsx
frontend/src/components/Workspace/FlowChart/Buttons/CreateWorkflow.tsx
frontend/src/components/Workspace/FlowChart/Buttons/RunButtons.tsx
frontend/src/components/Workspace/FlowChart/Dialog/ClearWorkflowIdDialog.tsx
frontend/src/components/Workspace/FlowChart/FlowChart.tsx
frontend/src/components/Workspace/ToolBar.tsx
frontend/src/components/common/ConfirmDialog.tsx
frontend/src/pages/AccountManager/index.tsx
frontend/src/pages/Workspace/index.tsx

Closes #162 
Confirm用のDialogの汎用コンポーネントを作成。
また、multiuserモードのユーザー登録Dialogなど、機能が複雑なDialogは適用対象外。
DialogTitle, DialogContent, DialogActionsをベースとして使用
- titleについてはoptional
- actionsのOKボタンはデフォルトではOKだが、labelConfirm属性でラベルを変更可能
- iconType属性で以下のようにwarning, infoのアイコン表示も実装
本実装にあたり、Dialogの文言なども簡易化した。

use common styled dialog ui

---

frontend/src/components/Workspace/FlowChart/FlowChartNode/NodeContainer.tsx

add nodeId copy button

---

studio/app/common/core/rules/runner.py
studio/app/optinist/core/nwb/nwb_creater.py

nwbfileのデータを前回のoutputから継承する際に、dictを上書きしてしまっている問題を解消
(tutorial作成作業中に発覚)
以下のようなworkflowで、etaのように新規のinputノード(ここではcsv)が接続されていると、nwbfileオブジェクトが上書きされてそれまでのノードで蓄積していたデータが消失する。
結果として、nwbファイルの保存時に以下のようなエラーとなっていた。
```
Traceback (most recent call last):
File "/Users/rei_hashimoto/GitHub/barebone-studio/studio/app/common/core/rules/runner.py", line 67, in run
cls.save_all_nwb(path, output_info["nwbfile"])
File "/Users/rei_hashimoto/GitHub/barebone-studio/studio/app/common/core/rules/runner.py", line 119, in save_all_nwb
overwrite_nwbfile(save_path, nwbconfig)
File "/Users/rei_hashimoto/GitHub/barebone-studio/studio/app/optinist/core/nwb/nwb_creater.py", line 406, in overwrite_nwbfile
nwbfile = set_nwbconfig(old_nwbfile, config)
File "/Users/rei_hashimoto/GitHub/barebone-studio/studio/app/optinist/core …
```

fix nwbfile data inheritance

---

.github/workflows/linters.yml

Python formatterのBlackによるGitHub Actionsがpre-releaseのversion(24)を参照してしまっているため、versionの上限を指定

specify black version for github actions

---

studio/app/common/dataclass/image.py
studio/app/common/dataclass/utils.py
studio/app/common/routers/outputs.py
studio/app/optinist/wrappers/suite2p/spike_deconv.py

Closes #242 
ver1.1へマージ予定。
algorithmのoutputにImageDataを含み、かつそのデータが動画(ndim==3)の場合について、jsonではなくtiffファイルのパスをoutput_pathとして設定するように修正
これによって、VISUALIZE Plotでindex指定した際に指定の範囲でのjsonが生成されるようになる。
デフォルトの範囲は0 ~ 10で、json生成済の範囲の場合は再参照する方式なので処理が軽減される。
- 現状該当するoutputはcaiman_mcのmc_imagesのみ
- #234 の対応でsuite2p_registrationのmc_imagesも追加予定
その他、各関数への影響確認中にsuite2p_spike_deconvでNWB保存の際のエラーが発覚したため本PR内で修正。（NWBへfunction_id単位でデータを保存する対応の際に漏れていた模様。）

[#242] outputの動画のrange指定機能修正

---

studio/config/docker/Dockerfile
studio/config/docker/Dockerfile.dev
studio/config/docker/Dockerfile.test

- python:3.8.16-slim -> python:3.8.18-slim

docker image verup

---

studio/app/optinist/microscopes/MicroscopeDataReaderBase.py
studio/app/optinist/microscopes/ND2Reader.py
studio/app/optinist/microscopes/test_ND2Reader.py
studio/config/docker/Dockerfile
studio/config/docker/Dockerfile.dev
studio/config/docker/Dockerfile.test

- PR内容
- 顕微鏡データReaderモジュールの初回push
- Nikon ND2用モジュール（構築途中）もpush
- 動作確認手順
- データの配置
- 以下dllのローカル環境配置（任意のパス）
- https://drive.google.com/drive/folders/1CUmHsBcbgGDsO3MjGW7gsO8IiuAb8kQg
- 以下テスト用データのローカル環境配置（任意のパス）
- https://drive.google.com/drive/folders/1LfrVe-3Dv9yZaj2uwj9Lyn_mGtP6O8Tz
- テストコード（test_ND2Reader.py）を pytest で実行可能
- テストコード内の設定（LIBRARY_DIR, TEST_DATA_PATH）で、上で配置した dll,テスト用データ, の格納パスを指定
- テストコードは Linux/Windows の両環境で動作可能
- レビュー観点
- 前提
- コード中TODO個所がいろいろとあるが、随時仕様確認中
- レビュー観点
- ここまでの実装段階（Nikonのmetadata取得まで）で、動作や構成が妥当であるかどうか？
- 備考
- この後の他フォーマット（Olympus, Inscopix）への対応により、ある程度I/Fの変更も想定される
- 当モジュールは、optinist には直接依存はしていないので、外部モジュール化も不可ではない

add microscope data reader modules (initial)

---

docker-compose.build.yml
docker-compose.dev.yml

Mac環境でFE buildのパフォーマンスが出ていなかったため、設定改善適用（volumeのcached利用）

improve docker volume performance (use cached)

---

frontend/src/components/Workspace/Experiment/Button/ReproduceButton.tsx
frontend/src/components/Workspace/FlowChart/Buttons/CreateWorkflow.tsx
frontend/src/components/Workspace/FlowChart/Buttons/ImportWorkflowConfig.tsx

- #181 
- #194 の対応で、チェックが漏れていた以下の内容を修正
- WORKFLOW tab
- create workflow, import workflow configのボタンが非活性になっていなかった
- RECORD tab
- reproduceが非活性になっていなかった

fix disable buttons while running workflow

---

studio/app/common/core/experiment/experiment_reader.py
studio/app/common/core/utils/config_handler.py

resolves #180 
- workflowなどのyaml保存の際に文字列のsortを無効化して対応しました
- 新規に作成・実行するワークフローでのみ事象が解消されます

fix not params to be sorted after reproduce

---

studio/app/common/core/rules/file_writer.py

resolve #161 
HDF5(nwb)に1次元の配列データとして保存されるIscellDataをHDF5ノードの入力として利用できるように修正
IscellDataとFluoDataが必要なcorrelationなどのアルゴリズムをnwbファイルをデータ入力として実行可能に

arrow 1d data from hdf5

---

frontend/src/components/Workspace/FlowChart/FlowChartNode/FlowChartUtils.ts
frontend/src/store/slice/HandleTypeColor/HandleTypeColorSlice.ts
studio/app/optinist/dataclass/__init__.py
studio/app/optinist/dataclass/spiking_activity.py
studio/app/optinist/wrappers/suite2p/spike_deconv.py

Resolves #177 
- suite2p_spike_deconvのoutputのデータ型を`FluoData`→`SpikingActivityData`に変更
- 機能としては`FluoData`と同様のため、継承して別名で作成
- 別名のdata typeを結合可能にするため`isValidConnection`を調整
本修正後に`FluoData`の入力ノードへの結合ができること、ワークフローが正常終了すること、結果に差異がないことを確認済。

spiking activity datatype

---

pyproject.toml
studio/app/optinist/microscopes/ThorlabsReader.py
studio/app/optinist/microscopes/test_ThorlabsReader.py

- Thorlabs Image Readerモジュール作成
- データの配置
- 以下テスト用データのローカル環境配置（任意のパス）
- https://drive.google.com/drive/folders/1Qsro6bL5A9QOPWEj1KcbxfEzg-L0_Ebh
- 現段階では、OME-TIFFディレクトリを そのまま配置する形式にのみ対応している。
- 今後、OME-TIFFディレクトリのZipアーカイブ形式へ対応予定（ユーザーへの要件確認＆Fix後に対応予定）
- 環境セットアップ
- 一部pythonモジュールを追加しているため、`poetry update` を事前に実施
- テストコード（test_ThorlabsReader.py）を pytest で実行可能
- テストコードは クロスプラットフォーム（Linux/Windows/Mac）で動作可能
- レビュー観点
- 動作や構成が妥当であるか
- 取得画像データのWorkfllow Nodeへの投入検証
- 関連
- Nikon PR:  #248
- Inscopix PR: #257
- Olympus PR: #281

Create Thorlabs image reader module

---

docker-compose.test.yml
pyproject.toml

PR #291 の Github Action での pytest が通らない件について、先に pyproject.toml の修正を develop-main へ当てておく必要がありそうであるため、このPRを発行します。

update pytest config

---

studio/app/optinist/wrappers/caiman/cnmf.py
studio/app/optinist/wrappers/caiman/cnmfe.py
studio/app/optinist/wrappers/caiman/params/caiman_cnmf.yaml
studio/app/optinist/wrappers/caiman/params/caiman_cnmfe.yaml

- 解説ドキュメント
- https://docs.google.com/presentation/d/1rYRKMhMmnARlEgWnOLT-T6iBQMYbqalr

added caiman advanced parameters

---

poetry.lock
pyproject.toml
studio/app/common/core/rules/file_writer.py
studio/app/optinist/core/nwb/nwb_creater.py
studio/app/optinist/dataclass/microscope.py
studio/app/optinist/wrappers/optinist/visualize_utils/microscope_to_img.py

ROI抽出を含むアルゴリズムを実行した際にNWBファイル保存時にエラーとなる事象を修正。
ROIのref先であるTwoPhotonSeriesが作成されていなかったことが原因。

fix microscope input nwb

---

sample_data/output/tutorial2/experiment.yaml
sample_data/output/tutorial2/snakemake.yaml
sample_data/output/tutorial2/workflow.yaml

- Tutorial2を実行する際に`check_types`でKeyErrorが発生する問題を修正
- caiman_cnmfに #300 などでパラメータが追加されたことに伴い、チュートリアルで使用しているyamlファイルのパラメータと不一致になっており、バリデーションで弾かれてしまった
- 最新版のcnmfノードに置き換えて実行した結果でTutorialファイルを差し替え

update tutorial data

---

frontend/src/components/Workspace/Visualize/Plot/ImagePlot.tsx

- ROIをclickした際にリンクしているfluorescenceのplotに反映されない問題を修正

fix roi select not working on linked plots

---

studio/app/common/dataclass/image.py
studio/app/const.py
studio/app/optinist/core/nwb/nwb_creater.py
studio/app/optinist/wrappers/caiman/__init__.py
studio/app/optinist/wrappers/caiman/cnmf.py
studio/app/optinist/wrappers/caiman/cnmf_multisession.py
studio/app/optinist/wrappers/caiman/params/caiman_cnmf.yaml
studio/app/optinist/wrappers/caiman/params/cnmf_multisession.yaml

メモリ消費が大きい場合の対策として、以下の実装を追加
- cnmf online
- 通常のcnmfのオプションとして実装
- `use_online`パラメータで切り替え
- online版のパラメータはadvancedに格納
- 分割した画像それぞれでcnmfを実行し、結果をregister multisessionで統合
- 画像の分割は画像サイズ(GB)を端数切り上げした値で行う
- 例:) 3.8GBの場合4ファイルに分割
- 1GB未満のファイルの場合、強制的に2分割する(register_multisessionでは2つ以上のsessionがないとエラーとなるため)
- 分割されたファイルの内、何割のファイルで共通して検出されたかによってregister_multisessionの結果をフィルタリングする
- reg_file_rateで割合を0.0 ~ 1.0の値で設定
- フィルタリングの結果ROI数が0の場合は後続の計算等ができないため、Exceptionとしている
(追記)
- Fluorescenceのcomments欄に以下の形式でreg_file_rateの情報を記載する形で対応

implement online cnmf and register_multisession

---

studio/app/optinist/wrappers/caiman/conda/caiman.yaml

現在の dependencies の構成で、caimanの処理でエラー（deprecatedのため）となるモジュールバージョン（scikit-image 0.20）がインストールされるケースがあるため、バージョンを明記する。
※今後、他のモジュールでも deprecated が生じた場合は、同様の対応を行う形を想定。

adjust caiman dependencies

---

studio/app/common/core/experiment/experiment_reader.py
studio/app/common/core/experiment/experiment_writer.py
studio/app/common/routers/experiment.py

- Contents
- So far, experiment data (a group of files) has been directly manipulated by file I/O in the API router, but now it is wrapped in ExptDataWriter to improve customizability.

Add ExptDataWriter

---

studio/app/common/core/experiment/experiment_writer.py

- A seek(0) was needed before file write in rename().
- On the surface, the problem was not visible, but an unexpected data append to experiment.yaml had occurred.

Fixed ExptDataWriter bug

---

docs/index.rst
docs/installation/mac.md

Add further explanation to documentation for running Optimist on Apple Silicon chips
Problem:
conda installations on M chips do not run correctly
Solution:
Install Intel-based conda (x86_64) using Rosetta2.

Update docs about x86_64 installation

---

studio/app/common/core/storage/mock_storage_controller.py
studio/app/common/core/storage/remote_storage_controller.py
studio/app/common/core/storage/s3_storage_controller.py
studio/app/common/routers/auth.py

- SingIn時処理 クラウドストレージ対応
- 主な改修ポイント
- SingIn時のExperiments Metadata (*.yaml) のダウンロード処理
- 詳細仕様
- https://docs.google.com/presentation/d/1Qvwfhk49bweP6uaqC-PCoCQUGGqZC78a/edit#slide=id.p8
- https://drive.google.com/file/d/1ssqWHzO5P42vIFy5WCziV2g6dM_YN89a/view?usp=drive_link
- s3_storage_controller.py 内の S3StorageController.download_all_experiments_metas() では、データのダウンロードに aws cli （外部コマンド）を利用しているが、妥当であるか
- pip module利用版（boto3）よりもプログラムードは簡潔となるが、外部コマンドへの依存が生じる
※別途準備想定

Implement downloading of config yaml from remote when singin

---

studio/app/common/core/experiment/experiment_writer.py

- Content
- Bug
- “r+” was used to open a file to be written, but the file truncation process was insufficient, and in some cases garbage remained at the end of the file.
- Solution
- Stopped using "r+" mode and simply used "r" -> "w" processing order.
- Related
- #366
- #369

fixed a bug in the rename of exepriment name

---

frontend/src/components/Workspace/Visualize/Plot/ImagePlot.tsx
frontend/src/components/Workspace/Visualize/VisualizeItem.tsx
frontend/src/store/slice/DisplayData/DisplayDataSelectors.ts
frontend/src/store/slice/DisplayData/DisplayDataSlice.ts
frontend/src/store/slice/DisplayData/DisplayDataType.ts
studio/app/optinist/core/edit_ROI/edit_ROI.py

- Optimize loading display
- Loading icon is not properly displayed in the ROI initial view.
- In cases where multiple APIs are executed concurrently, there was insufficient consideration for state management of loading icons, so this has been improved.
- Inadequate API error handling
- Improper error handling in commit_edit API (success is displayed even if 500 error, etc.)
- Control of the UI during "edit ROI" runs
- Workflow RUN should not be executed when “edit ROI” is committed (snakemake is run by backend).
- This was handled by displaying the loading icon in full screen when committing “edit ROI”.

Edit ROI UI improve bugfix

---

studio/app/common/core/utils/filepath_finder.py
studio/app/optinist/core/edit_ROI/edit_ROI.py
studio/app/optinist/routers/roi.py

- Support for s3 upload of processing results
- Supplemental specifications
- Only files that have been updated by edit roi (files that have been updated immediately before) are subject to upload.

add remote storage upload on edit roi

---

frontend/src/api/files/Files.ts

When uploading a large file to the AWS ECS environment, a Timeout occurred in some cases.
The following is a verification of each point at which timeouts may occur.
```
- client (frontend)
- browser (chrome, etc)
- library
- axios
- backend
- application
- fastapi
- uvicorn
- infra
- AWS
- ALB
- ECS
```
Of the above, the cause was the timeout setting in axios.
- /frontend/src/utils/axios.ts
```
const axios = axiosLibrary.create({
baseURL: BASE_URL,
timeout: 600000,
})
```
Extend timeout for file upload api. (10min -> 30min)

adjust axios timeout

---

studio/app/common/core/storage/mock_storage_controller.py
studio/app/common/core/storage/remote_storage_controller.py
studio/app/common/core/storage/s3_storage_controller.py
studio/app/common/routers/experiment.py
studio/tests/app/common/core/storage/test_remote_storage_controller.py

- Added automatic search for remote storage when there are no records in local.
- When the “Reload” button is pressed on the Record Screen, it works.
- A function that takes into account the case where a Docker container (AWS ECS container) is restarted and local data in the container is lost.
1. Prepare the state that there is a record in S3 and there is no record locally.
2. click the Reload button on the Record Screen
3. Confirm that the metadata of the records in S3 is downloaded and the list of records is displayed.

improve experiment metadata download

---

frontend/src/api/experiments/Experiments.ts
frontend/src/components/Workspace/Experiment/Button/DeleteButton.tsx
frontend/src/components/Workspace/Experiment/ExperimentTable.tsx
frontend/src/const/API.ts
frontend/src/store/slice/Pipeline/PipelineHook.ts
studio/app/common/core/experiment/experiment_writer.py
studio/app/common/routers/experiment.py
studio/app/common/routers/run.py
studio/app/common/routers/workflow.py
studio/app/optinist/routers/roi.py
studio/tests/app/common/core/experiment/test_expt_writer.py

- Improve API Error Handling
- Improved error handling in both backend and frontend when an exception occurs in some APIs, as it was insufficient in some APIs.
- backend ... Improved error handling and organized HTTP response codes
- frontend ... Appropriate message display in case of error
- Others
- improve frontend .env validation
- Related
- #467
The detailed Testcase is below
- If an Error occurs in the BackEnd (API) for the following operation, the error message (Snackbar) is properly displayed in the FrontEnd
- Workflow Run API error
- Workflow Fetch API error
- Experiment Reproduce API error
- Experiment Rename API error
- Experiment Delete API error
- Edit Roi Commit API error
However, since the above cases do not usually occur, the normal operation check is OK.
- Normal testcase …

Improve API Error Handling, etc

---

studio/app/common/core/workflow/workflow_runner.py
studio/app/common/routers/run.py

- Refactor logic of creating workflow unique_id
- Since the logic for creating workflow unique_id was written inline adhoc, it was explicitly made into a function.

Refactor logic of creating workflow unique_id

---

studio/app/common/core/snakemake/smk_utils.py
studio/app/common/core/storage/mock_storage_controller.py
studio/app/common/core/storage/remote_storage_controller.py
studio/app/common/core/storage/s3_storage_controller.py
studio/app/common/routers/experiment.py
studio/app/common/routers/files.py
studio/tests/app/common/core/storage/test_remote_storage_controller.py

In previous versions, input data uploaded by users was not synchronized to remote storage (S3).
In response to the above, we have added support for synchronizing input data to remote storage.
- Input data synchronization (upload) timing
- When a user uploads data to an input node
- Input data synchronization (download) timing
- When synchronizing (downloading) experiment data, input data is also downloaded
1. upload any input data
- -> confirm successful data upload to S3
2. execute workflow
- -> confirm successful processing and successful upload of data to S3
3. manually delete 1.(input data) and 2.(experiment data) data in local
4. synchronize (download) the record of 2. on the Record screen
- -> confirm success of synchronization (download) of 1.(input data) and 2.(experiment data)

Support input data uploading to remote storage

---

frontend/src/const/API.ts

*window.location.port was supposed to be empty for the default port.
- related
- #458

Fixed a bug in the checking logic of window.location.port

---

studio/config/docker/Dockerfile
studio/config/docker/Dockerfile.dev
studio/config/docker/Dockerfile.test

- Applied the same improvements as those made for the following issue (docker image size reduction)
- arayabrain/optinist-for-server#358
- The size of the Docker image was reduced by about 0.5GB (4GB → 3.5GB).
- confirm operation with `lccd`

update cleaning of conda cache in dockerfile

---

studio/app/common/core/rules/runner.py
studio/app/common/core/snakemake/smk_status_logger.py
studio/app/common/core/workflow/workflow_result.py
studio/app/common/routers/run.py
studio/app/common/schemas/workflow.py
studio/tests/app/common/core/workflow/test_workflow_result.py

- Refactoring
- #539
- Resolve abnormal workflow
- Fixed a potential bug in which the status check request from the frontend could not be completed indefinitely due to the execution status of the workflow.
- Added a mechanism to monitor process availability (use psutil)
- Other Improvements
- Support for cancel(kill) of processes in “conda env create” during workflow execution
- https://docs.google.com/spreadsheets/d/1n-xeQ6j2IOTS3f0yvSNEmW5zP6YmM4vs/

Resolve abnormal workflow

---

sample_data/output/tutorial1/experiment.yaml
sample_data/output/tutorial1/snakemake.yaml
sample_data/output/tutorial1/workflow.yaml
sample_data/output/tutorial2/experiment.yaml
sample_data/output/tutorial2/snakemake.yaml
sample_data/output/tutorial2/workflow.yaml

If the default value (input_0) is set for the ID of Input Node in Record, the following cases have been confirmed to cause problems.
- Cases where the problem occurs
1. modify the initial Node Type to be displayed in Workflow in frontend (e.g. Image -> Microscope)
2. execute the Workflow changed in 1.
3. Reproduce a past Record (with a different Input Type) → Crash in the frontend
- Cause of the problem
- When Reproducing a Record, there seems to be a lack of frontend validation for the case where “Nodes with the same ID but different types” exist on the Workflow screen.
As a temporary workaround, for Sample Data, apply a modification to make the Input Node ID a non-default value to avoid this case.
(Permanent measures will be considered separately as needed.)
- Run Workflow

Change input node id in sampledata (to a non-default value)

---

studio/app/common/wrappers/dummy/conda/dummy.yaml
studio/app/optinist/wrappers/caiman/conda/caiman.yaml
studio/app/optinist/wrappers/lccd/conda/lccd.yaml
studio/app/optinist/wrappers/optinist/conda/microscope.yaml
studio/app/optinist/wrappers/optinist/conda/optinist.yaml
studio/app/optinist/wrappers/suite2p/conda/suite2p.yaml

When snakemake uses conda env package yamls, the filename is hashed, as shown in the example below, making it difficult to easily identify which algo wapper a file is for from its filename.
```
.snakemake/conda/
- 5c61f0f4dea67b8c1e7b022a58022b1d_.yaml
- 9e28e80060a765af43d5e40f9a6f0aee_.yaml
- a8a8a954abda0e4ca4de364deca86b7f_.yaml
- fed0359ea0d88bd07ee86ded9ae35fae_.yaml
```
For this reason, add a header section to identify the algo in the yamls.
- Note:
- It is also possible to specify the "name" of the conda env in the package yml, but if you specify a name, the environment will not be rebuilt (it will be fixed) even if the package definition is changed, so the "name" section cannot be used for this requirement.

Added a header section to wrapper conda env package yamls

---

frontend/src/components/Workspace/Visualize/Plot/ImagePlot.tsx
frontend/src/components/Workspace/Visualize/Plot/TimeSeriesPlot.tsx

Modified the ROI color mapping to ensure consistent colors across different visualizations (heatmaps and time series plots). Previously, colors could appear differently between views due to different mapping formulas.
Key changes:
1. Created a unified color mapping function:
```typescript
function getRoiColor(roiIndex: number): string {
const colors = createColormap({
colormap: 'jet',
nshades: 200,
format: 'hex'
})
return colors[(Math.abs(roiIndex) * 9) % 200]
}
```
This function:
- Uses 200 distinct colors instead of 100 for finer gradation
- Multiplies the ROI index by 9 to spread consecutive ROIs further apart in the color spectrum
- Uses modulo 200 to wrap around when we exceed 200 ROIs
- Returns consistent hex colors
2. Replaced the old formula in TimeSeriesPlot:
```typescript
// …
```

consistent colour behaviour

---

docker-compose.yml
frontend/src/components/Workspace/FlowChart/FlowChart.tsx

- バックエンド
Wrappers配下に変更がある場合は、バックエンドがリロードされます。
- フロントエンド
CachedIconを追加。CachedIconがクリックされる時には、AlgoTreeを取得するためのAPIを呼び出します

[No.220-1]Improved method of adding new wrapper functions

---

frontend/src/components/Workspace/Visualize/Plot/HeatMapPlot.tsx

Fix for https://github.com/arayabrain/barebone-studio/issues/358
See issue for before and after heatmap plots

fix heapmap plot to not overlap with title

---

studio/app/common/core/logger.py
studio/app/common/core/rules/data.py
studio/app/common/core/rules/func.py
studio/app/optinist/core/rules/edit_ROI.py

For each script (.py) kicked from within the Snakefile, there were cases where exceptions were not caught (such as exceptions when importing a module), so exception handling has been improved.

Improved try-catch for scripts kicked from snakefile

---

studio/app/optinist/wrappers/caiman/conda/caiman.yaml
studio/app/optinist/wrappers/caiman/motion_correction.py
studio/app/optinist/wrappers/optinist/conda/microscope.yaml

When creating a conda env for caiman etc., an error occurred depending on the platform, so the package version specification was readjusted.

Adjust algo conda packages

---

sample_data/tutorial/output/tutorial3/experiment.yaml
sample_data/tutorial/output/tutorial3/snakemake.yaml
sample_data/tutorial/output/tutorial3/workflow.yaml

Fix node_id (input_0) in tutorial data  
*In folk repository (optinist-for-server), the default input node type is not Image, and duplicate node_ids are not allowed.

Fix node_id in tutorial data

---

studio/app/common/core/utils/pickle_handler.py
studio/app/common/core/workflow/workflow_result.py

- When generating a large pkl file (over 1GB, for example), there is a delay in writing the file (probably a few seconds). If there is a file read access (checking the end of the workflow) during writing, a pkl read error occurs.
- Reproducibility is not 100% (depending on the environment and timing)
Until the pkl file has been completely written, it cannot be read (this is handled by a temporary file)
1. Run All (Tutorial 1)
2. Run All (Microscope(.nd2 > 1GB) + suite2p_file_convert)

Support lock when writing pkl (implemented by rename)

---

docker-compose.dev.multiuser.yml
docker-compose.dev.yml
docker-compose.yml
frontend/src/components/Workspace/FlowChart/ModalLogs/index.tsx
studio/__main_unit__.py
studio/app/common/core/logger.py
studio/app/dir_path.py
studio/config/logging.multiuser.yaml
studio/config/logging.yaml

Change logs output dir
- Switch output destination to the path in the env var (OPTINIST_DIR)
- Adjustments to support logging in pip version
- Check point
1. Log files are output under $OPTINIST_DIR/logs.
2. Logs are displayed without delay in Log Viewer.
- Check target environments
- Native
- Development
- Pip
- Docker

Change logs output dir

---

frontend/src/components/Workspace/FlowChart/Buttons/CondaNoticeButton.tsx
frontend/src/components/Workspace/FlowChart/Buttons/NodesLinkButton.tsx
frontend/src/components/Workspace/FlowChart/FlowChart.tsx
frontend/src/components/Workspace/FlowChart/RightDrawer/AlgorithmParamForm.tsx
frontend/src/components/Workspace/FlowChart/RightDrawer/index.tsx
frontend/src/components/Workspace/FlowChart/TreeView.tsx
frontend/src/components/common/ResizebleSidebar.tsx
frontend/src/components/utils/CreateNodesUrlUtils.ts
frontend/src/const/Layout.ts

- Resizable Sidebar
- Algoの横にNode Url Linkの追加
https://github.com/user-attachments/assets/90ccbc78-7e60-4740-9ea7-f796959caffa

ResizableSidebar & Node URL Link

---

README.md
docs/index.rst

- Slackのコミュニティーの招待リンク追加
- Githubのリポジトリー追加

Add Slack and Github Repository to Top Page of ReadTheDocs

---

frontend/src/store/slice/Pipeline/PipelineHook.ts
frontend/src/store/slice/Pipeline/PipelineTestUtils.ts
frontend/src/store/slice/Pipeline/PipelineUtils.ts
studio/app/common/core/workflow/workflow_params.py
studio/app/common/routers/run.py

Fix for https://github.com/arayabrain/barebone-studio/issues/629

move snackbar error message to utils

---

studio/app/optinist/wrappers/caiman/caiman_utils.py
studio/app/optinist/wrappers/caiman/motion_correction.py

Some of the memmap files automatically generated by caiman cannot have their names changed. This can lead to file name duplications.
As mentioned above, the naming of some of the automatically generated files cannot be controlled, so we dealt with this by dynamically adjusting the storage folder for the automatically generated files.
The following rules were used to generate a temporary folder dedicated to caiman_mc.
- `f"{unique_id}_{function_id}"`
- Exapmle
```
$HOME/caiman_data/temp
19009979_caiman_mc_o5k0ez4d9p
f02f0e7f_caiman_mc_o5k0ez4d9p
```
- Testing platforms
- Native
- Docker
- Multiple simultaneous runs of caiman_mc to ensure no resource (memmap files) conflicts

Improved resource contention during parallel execution of caiman_mc

---

.gitignore
studio/app/optinist/core/nwb/nwb_loader.py
studio/app/optinist/core/nwb/optinist_data.py

Application起動時には、NWB moduleの初期化処理が実施されているが、初期化処理時に設定ファイル（namespace yaml）の生成が毎回行われており、複数のworker起動時に、ファイル生成のconflict＆NWB初期化失敗が発生するケースがあった。
初期化処理時の設定ファイル（namespace yaml）の生成を、並列化に対応。
具体的には、設定ファイルの生成に排他処理を導入した。
- Platforms
- Native
- Testcase
- Single Application Process (worker=1)
- Multi Application Process (worker>1)
- Other Testcase
- optinist-for-server
- ※別プロジェクトだが、Analysis Batch 内の NWB 処理に問題がないかをここで確認しておく

Supported nwb initialization concurrency

---

poetry.lock
pyproject.toml
studio/app/common/core/logger.py
studio/app/common/core/utils/log_reader.py
studio/config/logging.multiuser.yaml
studio/config/logging.yaml

optinist の並列化対応（multi-processing）の改善に伴い、logging も並列化に対応させる。
\*現在使用中の `logging.FileHandler` は、multi-processing に非対応である
- mutiprocessing下での標準的なlogging方式である、QueueHandler, QueueListener を検証。
- しかし以下のような課題があり、 optinsit (fastapi,uvicorn) には適合しないようであることを確認。
1. uvicorn の workers 毎のプロセスは、アプリケーションのコード管理外でプロセスが分離されており、worker間でloggingのQueue Stackを共有できない。
- 実際に動作検証すると、動作が不安定である模様。
2. また、QueueHandler と TimedRotatingFileHandler の組み合わせも、うまく連動していない？ようである。
上記から、他の方式を検討する。
- `concurrent_log_handler.ConcurrentRotatingFileHandler|ConcurrentTimedRotatingFileHandler` を検証
- 基本的には問題なく動作している模様
- しかし以下の様な課題も確認
1. 標準の TimedRotatingFileHandler に相当する ConcurrentTimedRotatingFileHandler の動作仕様が、TimedRotatingFileHandler とやや異なり、独自の動作仕様となっている
- 実際に動作検証すると、Rotation の動作（タイミングやbackup のnamingなど）などが異なる模様。
- …

Supported  logging concurrency

---

frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.test.tsx
frontend/src/components/Workspace/FlowChart/Dialog/FileSelectDialog.tsx

Previously, the delete button was only available on the Image input when multi-selection was enabled. This was limiting and inconsistent.
Now, single-select inputs can also display a delete button, providing a more flexible and user-friendly experience.
https://github.com/user-attachments/assets/f24af3b5-ffc5-4574-9334-806e00a3fc90

Add Delete Button to Tree Node Without Enabling Multi-Select

---

frontend/src/pages/Workspace/Workspace.tsx

When backend shut down while running workflow. Get workspace api if in infinite loop.
https://github.com/arayabrain/barebone-studio/issues/800
1. Run Tutorial 1. While running shutdown your backend system and check the network log to see the api access.
2. Test if Visualize state reset when changing workspace
　・You can test this by running tutorial 1 and wait to finish
　・Access Visualize and create any plot you want
　・Change Workspace and access Visualize Screen
Tested in

FIX Workspace Invalid API to loop.

---

studio/app/optinist/wrappers/optinist/dimension_reduction/cca.py
studio/app/optinist/wrappers/optinist/dimension_reduction/params/cca.yaml

>     cca = CCA(**params["CCA"])
> TypeError: __init__() got an unexpected keyword argument 'target_index'
Adding target_index to CCA instead of "I/O" in yaml. The target_index was then read by CCA and caused an error. 
Workflow containing CCA (use tutorial1 and change ETA for CCA)

CCA param added to wrong yaml section, caused error
