- studio/app/optinist/wrappers/__init__.py
- https://github.com/oist/optinist/issues/520
> Change algolist order

- frontend/src/components/Workspace/Visualize/Plot/ImagePlot.tsx
- studio/app/common/dataclass/timeseries.py
- studio/app/optinist/core/edit_ROI/wrappers/caiman_edit_roi/add_roi.py
- studio/app/optinist/core/edit_ROI/wrappers/caiman_edit_roi/delete_roi.py
- studio/app/optinist/core/edit_ROI/wrappers/caiman_edit_roi/merge_roi.py
- studio/app/optinist/core/edit_ROI/wrappers/lccd_edit_roi/add_roi.py
- studio/app/optinist/core/edit_ROI/wrappers/lccd_edit_roi/delete_roi.py
- studio/app/optinist/core/edit_ROI/wrappers/lccd_edit_roi/merge_roi.py
- studio/app/optinist/core/edit_ROI/wrappers/suite2p_edit_roi/delete_roi.py
- studio/app/optinist/core/edit_ROI/wrappers/suite2p_edit_roi/merge_roi.py
- studio/app/optinist/wrappers/caiman/cnmf.py
- studio/app/optinist/wrappers/caiman/motion_correction.py
- studio/app/optinist/wrappers/lccd/lccd_detection.py
- studio/app/optinist/wrappers/suite2p/roi.py
- https://github.com/oist/optinist/issues/517
> Make cell and flour ID start from 0

- frontend/src/api/experiments/Experiments.ts
- frontend/src/api/outputs/Outputs.ts
- frontend/src/components/Workspace/Visualize/Editor/TimeSeriesItemEditor.tsx
- frontend/src/components/Workspace/Visualize/Plot/TimeSeriesPlot.tsx
- frontend/src/store/slice/DisplayData/DisplayDataActions.ts
- frontend/src/store/slice/DisplayData/DisplayDataType.ts
- frontend/src/store/slice/Experiments/ExperimentsSelectors.ts
- frontend/src/store/slice/Experiments/ExperimentsType.ts
- frontend/src/store/slice/Experiments/ExperimentsUtils.ts
- frontend/src/store/slice/VisualizeItem/VisualizeItemSelectors.ts
- frontend/src/store/slice/VisualizeItem/VisualizeItemSlice.ts
- frontend/src/store/slice/VisualizeItem/VisualizeItemType.ts
- frontend/src/store/slice/VisualizeItem/VisualizeItemUtils.ts
- https://github.com/oist/optinist/issues/516
> add switch frames and time

- studio/app/optinist/core/nwb/nwb_creater.py
- studio/app/optinist/wrappers/caiman/__init__.py
- studio/app/optinist/wrappers/caiman/cnmf.py
- studio/app/optinist/wrappers/caiman/cnmfe.py
- studio/app/optinist/wrappers/caiman/params/caiman_cnmf.yaml
- studio/app/optinist/wrappers/caiman/params/caiman_cnmfe.yaml
- https://github.com/oist/optinist/issues/518
> add caiman cnmfe

- studio/app/optinist/core/nwb/nwb.yaml
Made edit on GCaMaP, and also edited the excitation wavelength to a more common one
https://github.com/oist/optinist/issues/546
> GCaMaP -> GCaMP

- docs/conf.py
Added copy function to readthedocs. Easier for users to copy code now
https://sphinx-copybutton.readthedocs.io/en/latest/index.html
> Added copy function to readthedocs

- Makefile
- docs/requirements.txt
- poetry.lock
- pyproject.toml
リリース手順の更新およびpoetryの導入に伴い、以下の対応を実施(更新後のリリース手順ドキュメントリンクはissueに記載)
- makeコマンドの内容修正
- リリース・ビルド用のパッケージ調整
また、ビルド対象を調整
- test_dataを除外
- sample_dataを追加
- #144 の対応の際に、ビルドされたパッケージでも参照可能である必要があるため
- なお、上記対応内でsample_dataの中身は整理し、容量を削減予定
> update release related files

- docker-compose.dev.yml
- studio/config/docker/Dockerfile
- studio/config/docker/Dockerfile.dev
- change COPY order (to maximize cache availability)
- adjust volume in docker-compose.dev.yml
- other minor corrections
> improve docker setting

- frontend/src/components/Workspace/FlowChart/Buttons/ClearWorkflow.tsx
- frontend/src/components/Workspace/ToolBar.tsx
- clear workflow→create workflow
- icon, tooltipのラベル, dialogのメッセージを更新
> update clear workflow icon and messages

- frontend/src/store/store.ts
> ignore serializable check for expected api error

- frontend/src/components/Workspace/Visualize/Plot/ImagePlot.tsx
> change rect select

- frontend/src/store/slice/DisplayData/DisplayDataSlice.ts
- pyproject.toml
- リリースの検証作業中に確認されたエラーの解消
- hasOwnPropertyの用法ミス
- sample_dataでネストされたファイルがパッケージに含まれていない問題
> fix errors found on release test

- frontend/src/components/Workspace/FlowChart/FlowChartNode/CsvFileNode.tsx
- frontend/src/components/Workspace/FlowChart/FlowChartNode/FileSelect.tsx
- studio/app/common/dataclass/csv.py
- studio/app/common/dataclass/timeseries.py
- studio/app/optinist/dataclass/behavior.py
- studio/app/optinist/dataclass/fluo.py
Closes #163 
- ver1.2でmerge予定
- csvのヘッダーがある場合のデータ取得方法を修正
- テスト用データ
- https://drive.google.com/drive/folders/1x3kS9H4hshr9vTs_PhUF45dD5H14CQxa?usp=drive_link
caiman + ETAでヘッダーあり、なしで分岐させて結果を比較
> fix csv with header

- studio/app/optinist/microscopes/.gitignore
- studio/app/optinist/microscopes/IsxdReader.py
- studio/app/optinist/microscopes/MicroscopeDataReaderBase.py
- studio/app/optinist/microscopes/ND2Reader.py
- studio/app/optinist/microscopes/test_IsxdReader.py
- PR内容
- Inscopix isxd Readerモジュール作成
- 動作確認手順
- Inscopix環境の構築
1. Inscopixパッケージをインストール
2. Python API 環境をセットアップ
- conda create env でのセットアップ
- 具体的な手順はマニュアルを参考
- データの配置
- 以下テスト用データのローカル環境配置（任意のパス）
- https://drive.google.com/drive/folders/1TOlkOHxMOm7lfJLVYG5w96Ju3KfGUc3N
- テストコード（test_IsxdReader.py）を pytest で実行可能
- テストコード内の設定（TEST_DATA_PATH）で、上で配置した テスト用データ, の格納パスを指定
- テストコードは Linux/Windows の両環境で動作可能
- レビュー観点
- レビュー観点
- 動作や構成が妥当であるか
- 取得画像データのWorkfllow Nodeへの投入検証
- 想定課題
- Inscopix導入手順・環境構成をどうするか
- 利用には Inscopix 本体のインストールや、conda create env が必要
- optinist や snakemake とどの様に協働させるか、要設計
- 確認している注意点
- `conda init bash` を行うと、glibc等のパスが変化し、他のReader(Nikon, Olympus)のDLLが動作しないケースがある (問題ないケースもある？)
- Inscopix APIのPython利用バージョンは、3.10 (optinistのpythonバージョンと異なる)
> create Inscopix isxd reader module

- studio/app/optinist/microscopes/IsxdReader.py
- studio/app/optinist/microscopes/MicroscopeDataReaderBase.py
- studio/app/optinist/microscopes/ND2Reader.py
- studio/app/optinist/microscopes/OIRReader.py
- studio/app/optinist/microscopes/test_IsxdReader.py
- studio/app/optinist/microscopes/test_ND2Reader.py
- studio/app/optinist/microscopes/test_OIRReader.py
顕微鏡データモジュールについて、軽微なリファクタリングとbugfixを適用
> apply minor refactoring and bugfix

- studio/app/optinist/microscopes/.gitignore
- studio/app/optinist/microscopes/IsxdReader.py
- studio/app/optinist/microscopes/MicroscopeDataReaderBase.py
- studio/app/optinist/microscopes/ND2Reader.py
- studio/app/optinist/microscopes/OIRReader.py
- studio/app/optinist/microscopes/ThorlabsReader.py
- studio/app/optinist/microscopes/modules/olympus/scanner_settings.py
- studio/app/optinist/microscopes/tests/test_IsxdReader.py
- studio/app/optinist/microscopes/tests/test_ND2Reader.py
- studio/app/optinist/microscopes/tests/test_OIRReader.py
- studio/app/optinist/microscopes/tests/test_ThorlabsReader.py
- リファクタリング
- テストコード リファクタリング
- Inscopix Isx Reader
- isxモジュール IDPS版とOSS版 との互換性確保
- この対応により、基本的にOSS版のみでIsx Readerを利用可能となる
- OSS版のテストコードで、 image save でエラー発生
- 環境セットアップ（pillow）の問題の可能性もある。調査中
- → isx module間で仕様差異があることを確認。差異を吸収する調整を適用し対処（画像データのdtypeの調整）
- Olympus OIR Reader
- framerate のメタデータを取得するよう調整（対応するmetadataからの取得）
> Refactor microscope modules

- studio/app/optinist/microscopes/IsxdReader.py
- studio/app/optinist/microscopes/MicroscopeDataReaderBase.py
- studio/app/optinist/microscopes/ND2Reader.py
- studio/app/optinist/microscopes/OIRReader.py
- studio/app/optinist/microscopes/ThorlabsReader.py
- update metadata field name (imaging_rate)
> microscopes) update metadata field name (imaging_rate)

- studio/app/optinist/wrappers/caiman/cnmf.py
non_cellがnon_cellのROIではなく、backgroundを表示していた問題を修正。
> fix noncell shows background

- frontend/src/components/Workspace/Experiment/ExperimentStatusIcon.tsx
- frontend/src/components/Workspace/FlowChart/FlowChart.tsx
以下PRと同内容
- https://github.com/arayabrain/optinist-for-server/pull/286
> apply pre-wrap to node error messages

- studio/app/optinist/wrappers/caiman/cnmf.py
- studio/app/optinist/wrappers/lccd/lccd_detection.py
NWBファイルの問題2件を修正
1. caimanのiscellデータがfloatになっている
2. lccdのfluorescenceデータが転置されておらず、CNMFやSuite2pの形状(time x cell)と一致しない
> fix nwb data

- studio/app/optinist/microscopes/ND2Reader.py
Confirmed the exact method of obtaining physical_size and reflected it.
- Same content PR
- https://github.com/arayabrain/optinist-for-server/pull/301
> microscope) adjust calculation method of physical_size

- Makefile
リリースに使用するコマンドを調整
- version等の引数に対応してmakeで完結可能なコマンドを増やした
- 一部コマンド名の調整
下記のリリース手順ドキュメントも対応するように更新
- https://drive.google.com/file/d/1loT0dP8x-PlI_tQLxt7SMI9xSSDsa76J/view?usp=drive_link
> improve make commands for release

- studio/app/common/dataclass/image.py
- studio/app/const.py
- studio/app/optinist/wrappers/caiman/cnmf_multisession.py
- studio/app/optinist/wrappers/caiman/params/cnmf_multisession.yaml
- register_multisession #332  での分割ファイル数をファイルサイズからの判定ではなくユーザー指定の値を採用するように変更。
> use n_reg_files to specify split count

- pyproject.toml
- studio/app/optinist/microscopes/ND2Reader.py
- studio/app/optinist/microscopes/OIRReader.py
> remove microscope libs from package

- studio/__main_unit__.py
- studio/app/common/core/logger.py
- studio/config/logging.multiuser.yaml
- studio/config/logging.yaml
- enable debug level for optinist-logger
- adjust logging-format
> improve logger

- studio/app/Snakefile
- studio/app/common/core/rules/runner.py
- studio/app/common/core/snakemake/snakemake_rule.py
- add rule name for each rules
- add validation for node input data
> improve snakemake runner

- studio/app/Snakefile
- studio/app/common/core/rules/data.py
- studio/app/common/core/snakemake/smk_utils.py
- studio/app/common/core/workflow/workflow.py
- studio/app/common/core/workflow/workflow_runner.py
- studio/app/common/routers/files.py
- studio/app/common/routers/outputs.py
- studio/app/const.py
- Clarify definition and determination of NodeType (Data or Algo)
- The definitions of NodeType and FileType and the process of identifying them were somewhat confusing, so they were improved.
- Refactored definition and operation of ACCEPT_FILE_EXT
- Use Enum, simplify implementation
Execute the following workflow and confirm that the output is the same before and after the modification.   
*Since there are slight errors in processing results each time due to decimal points, etc., this point is ignored.
- Pattern
- suite2p (file_convert > registration > ROI)
- caiman (mc > cnmf)
- tutorial (# 2)
- input microscope
> improve workflow runner

- .vscode/settings.example.json
- Details
- add vscode settings for prettier/frontend
- Expected behavior
- save files such as .tsx, .ts, etc in vscode
-  -> prettier auto format is applied
> update vscode settings (for prettier)

- docker-compose.dev.multiuser.yml
- docs/host_for_multiuser/setup.md
- docs/installation/docker_for_developer.md
- docs/installation/each_platforms_for_developer.md
- studio/config/.env.example
- studio/config/docker/Dockerfile
- studio/config/docker/Dockerfile.dev
- studio/config/docker/Dockerfile.test
- Contents
- Update settings
- Add `docker-compose.dev.multiuser.yml` to use multiuser mode in docker.
- Applied patch to Dockerfile (fixed unavailability of alembic command)
- Update docs
- Updated multiuser mode setup documentation. ( `host_for_multiuser/setup.md` )
- Added clear setup instructions for docker.
- Corrected other errors and confusing parts.
- Testing
- Confirmed that "docker + multiuser mode" can be setup by following the documentation and using above docker-compose yaml.
- Converted results to HTML (sphinx) also confirmed.
> Update settings and docs for multiuser mode

- docs/host_for_multiuser/setup.md
Support for internal linking in multiple environments (markdonw,sphinx) by making the number at the beginning of the anchor destination text a special character
- Testcase
> modify doc internal link

- studio/app/common/core/experiment/experiment.py
- studio/app/optinist/core/edit_ROI/edit_ROI.py
- studio/app/optinist/wrappers/caiman/cnmf.py
- studio/app/optinist/wrappers/caiman/cnmf_multisession.py
- studio/app/optinist/wrappers/caiman/motion_correction.py
- studio/app/optinist/wrappers/lccd/lccd_detection.py
- studio/app/optinist/wrappers/optinist/basic_neural_analysis/eta.py
- studio/app/optinist/wrappers/optinist/dimension_reduction/cca.py
- studio/app/optinist/wrappers/optinist/dimension_reduction/dpca_fit.py
- studio/app/optinist/wrappers/optinist/dimension_reduction/pca.py
- studio/app/optinist/wrappers/optinist/dimension_reduction/tsne.py
- studio/app/optinist/wrappers/optinist/neural_decoding/glm.py
- studio/app/optinist/wrappers/optinist/neural_decoding/lda.py
- studio/app/optinist/wrappers/optinist/neural_decoding/svm.py
- studio/app/optinist/wrappers/optinist/neural_population_analysis/correlation.py
- studio/app/optinist/wrappers/optinist/neural_population_analysis/cross_correlation.py
- studio/app/optinist/wrappers/optinist/neural_population_analysis/granger.py
- studio/app/optinist/wrappers/suite2p/file_convert.py
- studio/app/optinist/wrappers/suite2p/registration.py
- studio/app/optinist/wrappers/suite2p/roi.py
- studio/app/optinist/wrappers/suite2p/spike_deconv.py
- Contents
- add parser (ExptOutputPathIds)
- Test case
- Verify that the modified part of the process goes through
- Mainly wrapper related
- Not all wrappers have been run, but major ones have been checked (suite2p, caiman, tutorial, etc)
> Add a parser for each ID in the experiment output data path

- frontend/src/components/Workspace/Experiment/Experiment.tsx
- frontend/src/store/slice/FlowElement/FlowElementSlice.ts
Apply additional updates to #376 
- Modifications
- Add new loading icon display
- Record screen
- reproduce workflow
- Test case
- \*Check the loading icon on the above screen.
> add loading icon for fetch workflow api

- Makefile
- Minor adjustments
- Add header comments
- Change `docker compose` command to modern format
- Functional Improvements
- Adjusted build_frontend to work properly
- Adjustment of useless container removal behavior
- Removed --remove-orphans from `docker compose down`
- Added rm_unused_docker_containers function
- Confirmed that github action make test_run passes
> Update optinist Makefile

- studio/app/optinist/wrappers/suite2p/conda/suite2p.yaml
- Contents
- Stabilize and speed up create env (mainly for apple sillicon machine)
- Test
- Check if there are any improvements to the issues in the #365
- PS) Confirmation that this matter has not been resolved. Continued to address the issue.
> improve suite2p conda yaml

- studio/tests/app/common/core/storage/test_remote_storage_controller.py
- test execute command
```sh
poetry run pytest -s studio/tests/app/common/core/storage/test_remote_storage_controller.py 
```
> add test_remote_storage_controller

- frontend/package.json
> patch for jest run

- frontend/src/components/Layout/Header.tsx
- frontend/src/pages/Login/index.tsx
- studio/app/common/core/auth/auth.py
- studio/app/common/routers/auth.py
Adjusted header icon display in multiuser mode
- Improved handling of authentication errors
- ac7c7e5
> Until now, only one error message was displayed during authentication ("Email or password is wrong"), but this has been improved to display a message that is easier to understand.
> There are now two types of messages displayed (1. Authentication error, 2. Unexpected error)
- Adjusted header icon display in multiuser mode
- f8e3958
- Changes
- ![image](https://github.com/user-attachments/assets/876e4d4b-97f7-49dd-a9d1-173a22662de5)
- The red box above is also displayed in multiuser mode.
> Improvements in auth and minor ui

- studio/config/docker/Dockerfile
- studio/config/docker/Dockerfile.dev
> Apply dockerfile adjustment for aws ecs

- studio/app/common/core/storage/mock_storage_controller.py
- studio/app/common/core/storage/s3_storage_controller.py
- studio/tests/app/common/core/storage/test_remote_storage_controller.py
- Unuse aws cli for downloading data from s3 (sync on SignIn)
> Improved download process of Experiments metadata

- cloud-startup.sh
- Refactored startup script to run application and load balancer check concurrently
- Removed blocking load balancer check before application start
- Added background process for load balancer health check
- Increased robustness of load balancer check with retry mechanism
> simultaneous check load balancer and startup

- studio/app/common/core/snakemake/snakemake_executor.py
- studio/app/common/core/storage/mock_storage_controller.py
- studio/app/common/core/storage/remote_storage_controller.py
- studio/app/common/core/storage/s3_storage_controller.py
- studio/app/common/core/workflow/workflow_runner.py
- studio/app/common/routers/experiment.py
- studio/app/common/routers/workflow.py
- studio/app/optinist/core/edit_ROI/edit_ROI.py
- studio/tests/app/common/core/storage/test_remote_storage_controller.py
- Update remote_sync_stat_file operation
- refactor remote-sync-status names
- adjust update timing of remote-sync-status file
- Organize remote_sync_status management during workflow execution
- Measures for irregular API requests (browser reload, etc.)
- Upload to remote storage when importing sample data
User testing is sufficient with basic operational checks.
- Normal testcase
- Workflow Screen
- Run
- Run All
- and S3 data synchronization
- Experiment Screen
- Reproduce
- Rename
- Delete
- and S3 data synchronization
- Visualize Screen
- Edit Roi
- and S3 data synchronization
> Improve remote storage state control

- studio/app/common/core/experiment/experiment.py
- studio/app/common/core/experiment/experiment_reader.py
- studio/app/common/core/experiment/experiment_writer.py
- studio/app/common/core/rules/func.py
- studio/app/common/core/rules/runner.py
- studio/app/common/core/snakemake/smk_status_logger.py
- studio/app/common/core/snakemake/snakemake_executor.py
- studio/app/common/core/snakemake/snakemake_writer.py
- studio/app/common/core/utils/pickle_handler.py
- studio/app/common/core/workflow/workflow.py
- studio/app/common/core/workflow/workflow_result.py
- studio/app/common/core/workflow/workflow_runner.py
- studio/app/common/core/workflow/workflow_writer.py
- studio/app/common/routers/run.py
- studio/tests/app/common/core/experiment/test_expt_reader.py
- studio/tests/app/common/core/snakemake/test_snakemake_executor_lccd.py
- studio/tests/app/common/core/snakemake/test_snakemake_executor_suite2p.py
- studio/tests/app/common/core/snakemake/test_snakemake_writer.py
- studio/tests/app/common/core/workflow/test_workflow_result.py
- Refactoring workflow result related processing
- Improved code visibility
- Improved and proper status monitoring of Workflow/Node processing
- refactor ConfigWriter modules
- refactor workflow pid file processing
- refactor cancel workflow processing
- etc.
- Run ALL
- Run
> Refactor workflow result processing

- studio/app/common/core/experiment/experiment.py
- studio/app/common/core/experiment/experiment_reader.py
- studio/app/common/core/experiment/experiment_writer.py
- studio/app/common/core/rules/func.py
- studio/app/common/core/rules/runner.py
- studio/app/common/core/snakemake/smk_status_logger.py
- studio/app/common/core/snakemake/snakemake_executor.py
- studio/app/common/core/snakemake/snakemake_writer.py
- studio/app/common/core/utils/pickle_handler.py
- studio/app/common/core/workflow/workflow.py
- studio/app/common/core/workflow/workflow_result.py
- studio/app/common/core/workflow/workflow_runner.py
- studio/app/common/core/workflow/workflow_writer.py
- studio/app/common/routers/run.py
- studio/tests/app/common/core/experiment/test_expt_reader.py
- studio/tests/app/common/core/snakemake/test_snakemake_executor_lccd.py
- studio/tests/app/common/core/snakemake/test_snakemake_executor_suite2p.py
- studio/tests/app/common/core/snakemake/test_snakemake_writer.py
- studio/tests/app/common/core/workflow/test_workflow_result.py
- Refactoring
- #539
- Resolve abnormal workflow
- *WIP
> Resolve abnormal workflow

- studio/config/docker/Dockerfile.test
- Replace `poetry install` to `poetry export & pip install` for Dockerfile.test
> improve Dockerfile.test

- frontend/src/components/Workspace/ToolBar.tsx
- frontend/src/components/Workspace/WorkspaceTabs.tsx
- added link back to workspaces (for multi-user mode)
> adjust header navigation: added link back to workspaces

- studio/app/optinist/wrappers/caiman/cnmf.py
change caiman indx as being flagged by codespell
> changed indx to idx

- studio/app/optinist/core/nwb/nwb_creater.py
- contents
- organize function and variable names
- adjust comments
> Refactoring edit roi codes

- Makefile
作業内容
- push_dockerhubを利用する時にversion tagを指定する。
- 現状のVersionとLatestVersionを２つDocker Hubにアップロードします
> old version to be save when push_dockerhub is used

- studio/app/common/core/rules/runner.py
- studio/app/common/core/workflow/workflow_result.py
1. bugfix
-  Improved platform dependency (Enhanced windows platform support)
2. improvement
- performance improvement, etc.
> Improve workflow monitor

- docs/conf.py
- frontend/package.json
- pyproject.toml
- studio/app/common/core/experiment/experiment.py
- studio/app/common/core/rules/runner.py
- studio/app/common/core/workflow/workflow_result.py
- studio/app/optinist/wrappers/caiman/cnmf.py
- hotfix import from arayabrain/barebone-studio#590 to main branch
> hotfix windows native error

- frontend/src/store/slice/DisplayData/DisplayDataSlice.ts
- frontend/src/store/slice/DisplayData/DisplayDataUtils.ts
- studio/app/common/dataclass/timeseries.py
- studio/app/common/routers/outputs.py
- studio/app/optinist/core/edit_ROI/wrappers/caiman_edit_roi/commit.py
- studio/app/optinist/core/edit_ROI/wrappers/caiman_edit_roi/utils.py
- studio/app/optinist/core/edit_ROI/wrappers/lccd_edit_roi/commit.py
- studio/app/optinist/core/edit_ROI/wrappers/lccd_edit_roi/utils.py
- studio/app/optinist/core/edit_ROI/wrappers/suite2p_edit_roi/commit.py
- studio/app/optinist/core/edit_ROI/wrappers/suite2p_edit_roi/utils.py
- studio/app/optinist/wrappers/caiman/cnmf.py
- studio/app/optinist/wrappers/lccd/lccd_detection.py
- studio/app/optinist/wrappers/suite2p/roi.py
Added fixes to roi detection outputs to handle cases when roi = 0, and changed timeseries dataclass to accept this too
> Fix roi = 0 

- frontend/src/components/Workspace/FlowChart/FlowChart.tsx
問題：
Updating the algo list while a workflow is running will result in a run error.
解決方法（実装内容）：
Refresh NodeをWorkflow中に無効化しました。
> Refresh NodeをWorkflow中に無効

- docs/installation/appendix.md
- docs/installation/users/windows_wsl.md
内容
WindowsのWSLでOptinistを立ち上げる時に不足している情報があるため、
Docsを更新する必要がありました。
参照：https://araya.slack.com/archives/C04J51TUWJW/p1740620695478659?thread_ts=1740611871.998229&cid=C04J51TUWJW
> WindowsのWSLのドキュメントを修正

- frontend/src/components/Workspace/FlowChart/Buttons/CondaNoticeButton.tsx
Improved the problem that the setup conda env button process was not properly stopped if an error occurred during the process.
> improve setup conda error handling

- frontend/src/store/slice/VisualizeItem/VisualizeItemActions.ts
https://github.com/user-attachments/assets/587d93f2-bc2f-442c-87d4-87b4942f58f3
> 666 Roi + Fluo Drag Select is not working

- frontend/src/components/Workspace/FlowChart/FlowChart.tsx
- frontend/src/components/Workspace/Visualize/Visualize.tsx
- frontend/src/components/common/LeftSidebarContainer.tsx
- frontend/src/const/Layout.ts
【Content】
- Add vertical scrolling to the Left
- Creating Component for LeftSidebarContainer
> Add vertical scrolling to the Left

- studio/app/common/core/snakemake/smk_utils.py
Suppressed flake8 error that occurred depending on the environment (unnecessary global specification)
> Suppressed flake8 error

- studio/app/common/db/database.py
- Refactor database module
- Changed access to database objects from global variables to getter functions (change to accommodate parallelization)
- Database engine instances are cached (lru_cache)
- CRUD operations are possible using Workspaces Screen, etc.
> Refactor database module

- docs/gui_guide/visualize.md
- docs/index.rst
- docs/specifications/algorithm_nodes.md
- Added Docs Not for Lazy Loading in Movies
> Added Docs Not for Lazy Loading in Movies

- studio/app/common/core/workflow/workflow_runner.py
When filtering data, NWB file saving style:
* ophys
* ImageSegmentation
* **filtered_**caiman_cnmf_xxxx (id...iscell)
* caiman_cnmf_xxxx (id...iscell)
* **filtered_**caiman_cnmf_xxxx
* Fluorescence (data, rois, ...)
*  caiman_cnmf_xxxx
*  Fluorescence (data, rois, ...)
* optinist
* **filtered_**caiman_cnmf_xxxx_filter_roi_ind
* **filtered_**caiman_cnmf_xxxx_filter_time_ind
> Save filtered nwb files

- studio/app/common/core/rules/runner.py
- studio/app/optinist/core/nwb/nwb.py
- studio/app/optinist/core/nwb/nwb_creater.py
- studio/app/optinist/core/nwb/optinist_data.py
When running a node, conda env yaml and node params are converted to json string and saved.
> Conda yaml and node params to nwb

- studio/app/common/core/workflow/workflow_result.py
Should we remove debugging log?
> Comment out debugging log for pid

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/problem.md
- .github/ISSUE_TEMPLATE/task.md
- .github/PULL_REQUEST_TEMPLATE/pr.md
Updated github issue/pr templates
- issues templates
- feature_request
- problem
- task
- pr templates
- pr (default)
> Updated github issue/pr templates

- docs/gui_guide/record.md
changing data usage to data size.
I forgot some of it into documents therefor, I updated docs
> fixing data usage to data size

- studio/app/common/core/workspace/workspace_services.py
- studio/app/common/routers/experiment.py
- Applying code refactoring to `feature/delete_enhancement`
- Consolidating experiment data deletion into delete_workspace_experiment
- Consolidating workspaces data deletion into delete_workspace_contents
> Refactor feature/delete_enhancement

- .github/workflows/tests.yml
- Add develop-feature to GitHub Actions test runs
> Update github workflows/tests setting

- docs/conf.py
- frontend/package.json
- pyproject.toml
- studio/app/optinist/core/nwb/specs/optinist.namespace.yaml
- v2.3.0 Released
- https://github.com/arayabrain/barebone-studio/milestone/16
*The reflection of this version in OIST/optinist will be skipped for the time being, so this time the release work will be done only within barebone-studio.
> Release v2.3.0

- studio/app/common/core/rules/runner.py
- Runner improvements for data manipulators
- Improved input info reading (avoiding duplicate data keys)
- Solution
- When reading the input info (.pkl) at the start of each node processing, the node ID is taken into consideration to eliminate the possibility of duplicate input info keys.
- `runner.Runner`
- `__read_input_info`, `__align_input_info_content_keys`
- #809
- This PR addresses the generalization and refactoring of the process implemented below.
- e6d8d67
- The workflow affected by this issue
- #809
- > data_slice: ValueError: Too many slice specs provided (4 for 3 dimensions)
- > eta: TypeError: ETA() missing 1 required positional argument: 'behaviors_data'
Even with the fix in this PR, only data_slice is not working.
- Cause
- The appropriate field name ("sliced_data") is not …
> Runner improvements for data manipulators
